#GET all users
GET http://localhost:8080/api/user
Accept: application/json

###

#GET user by id
GET http://localhost:8080/api/user/1
Accept: application/json

###

#POST user
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "username": "jano28",
  "email": "jano@gmail.com",
  "password": "sadsffafdsa",
  "role": 1
}

###

#DELETE user
DELETE http://localhost:8080/api/user/3
Accept: application/json

###

#PUT user
PUT http://localhost:8080/api/user
Content-Type: application/json

{
  "id": 1,
  "username": "jano99",
  "email": "jano@gmail.com",
  "password": "sadsffafdsa",
  "role": 1
}

###

#GET all users details
GET http://localhost:8080/api/user/details
Accept: application/json

###

#GET  users details by id
GET http://localhost:8080/api/user/details/1
Accept: application/json

###

#POST user details
POST  http://localhost:8080/api/user/details
Content-Type: application/json

{
  "firstname": "sasasa",
  "lastname": "Sasasasa",
  "height": 185,
  "weight": 90,
  "age": 22,
  "goal": "gain",
  "user": 6,
  "training": 1,
  "diet": 1
}

###



#PUT user details
PUT  http://localhost:8080/api/user/details
Content-Type: application/json

{
  "firstname": "Jano",
  "lastname": "Maly",
  "height": 146,
  "weight": 90,
  "age": 22,
  "goal": "gain",
  "user": 6,
  "training": 1,
  "diet": 1
}

###


#GET all diets
GET http://localhost:8080/api/diet
Accept: application/json

###

#GET diet by id
GET http://localhost:8080/api/diet/1
Accept: application/json

###


#GET all exercises
GET http://localhost:8080/api/exercise
Accept: application/json

###

#GET exercise by id
GET http://localhost:8080/api/exercise/1
Accept: application/json

###

#GET all exercise muscles
GET http://localhost:8080/api/exercise/muscle
Accept: application/json

###

#GET exercise muscle by id
GET http://localhost:8080/api/exercise/muscle/1
Accept: application/json

###

#GET all foods
GET http://localhost:8080/api/food
Accept: application/json

###

#GET  food by id
GET http://localhost:8080/api/food/1
Accept: application/json

###

#GET all food diets
GET http://localhost:8080/api/food/diet
Accept: application/json

###

#GET food diet by id
GET http://localhost:8080/api/food/diet/1
Accept: application/json

###


#GET all food nutrients
GET http://localhost:8080/api/food/nutrient
Accept: application/json

###

#GET food nutrient by id
GET http://localhost:8080/api/food/nutrient/1
Accept: application/json

###


#GET all muscles
GET http://localhost:8080/api/muscle
Accept: application/json

###

#GET muscle by id
GET http://localhost:8080/api/muscle/1
Accept: application/json

###


#GET all nutrients
GET http://localhost:8080/api/nutrient
Accept: application/json

###

#GET nutrient by id
GET http://localhost:8080/api/nutrient/1
Accept: application/json

###


#GET all trainings
GET http://localhost:8080/api/training
Accept: application/json

###

#GET training by id
GET http://localhost:8080/api/training/1
Accept: application/json

###


#GET all training exercises
GET http://localhost:8080/api/training/exercise
Accept: application/json

###

#GET training exercise by id
GET http://localhost:8080/api/training/exercise/1
Accept: application/json

###