INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (191,'Barbell Suitcase Carry Video Exercise Guide','Forearms','Strength','Barbell','Compound','Isometric','Beginner','Abs, Hamstrings, Lower Back, Quads, Shoulders, Traps, Upper Back','The barbell suitcase carry is a variation of the farmer’s carry and an exercise used to strengthen the muscles of the core and forearms.
The barbell suitcase carry gets its name because when you perform the exercise you hold the barbell like you would hold a suitcase.','Load a barbell and set up perpendicular to the bar.
Grasp the bar with a neutral grip and stand up straight.
While maintaining an active shoulder position, hold the barbell by your side and walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
If performing a unilateral carry variation, ensure that you’re not leaning to one side as you complete the movement.
Shrug the shoulder just slightly. Not enough so that it takes above a position of neutral but just enough to offset the weight pulling your shoulders down.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.','https://www.youtube.com/embed/xv1i_0uIGDM?rel=0','https://cdn.muscleandstrength.com/sites/default/files/barbell-suitcase-carry.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (192,'Dumbbell Farmers Carry Video Exercise Guide','Forearms','Strength','Dumbbell','Compound','Isometric','Beginner','Abs, Hamstrings, Lower Back, Quads, Shoulders, Traps, Upper Back','The farmers carry is a total body exercise that builds strength in the forearms, traps, and core.
Carries are a foundational movement pattern and are important to include in your workout routines to build optimal strength.
The movement works through isometric contraction on the forearms and traps. It also provides a core challenge as you try to maintain a stable spine while walking the prescribed distance.
The farmers carry can be included in nearly any workout routine.','Grasp a dumbbell in each hand using a neutral grip and stand up straight.
While maintaining an active shoulder position, hold the dumbbells by your side and walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
If performing an unilateral carry variation, ensure that you’re not leaning to one side as you complete the movement.
Shrug the shoulders just slightly. Not enough so that it takes above a position of neutral but just enough to offset the weight pulling your shoulders down.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.','https://www.youtube.com/embed/j8c9uNjr7nQ?rel=0','https://cdn.muscleandstrength.com/sites/default/files/dumbbell-farmers-carry.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (193,'Dumbbell High Low Carry Video Exercise Guide','Forearms','Strength','Dumbbell','Compound','Isometric','Intermediate','Abs, Hamstrings, Lower Back, Quads, Shoulders, Traps, Upper Back','The dumbbell high low carry is a variation of the farmers walk and an exercise used to strengthen the core and shoulders.
The unilateral loading seen in the dumbbell high low carry forces your core to fight to stabilize the spine.','Grasp a dumbbell in each hand using a neutral grip and stand up straight.
Clean and press one of the dumbbells overhead and hold the other by your side to get into position.
While maintaining an active shoulder position, maintain one dumbbell overhead and walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
If performing a unilateral carry variation, ensure that you’re not leaning to one side as you complete the movement.
Shrug the shoulder of the down arm just slightly. Not enough so that it takes above a position of neutral but just enough to offset the weight pulling your shoulders down.
If you sit in a position of heavy scapular depression, you may find that a slight shrug of the shoulder is necessary to get adequate upward rotation of the scapula and ensure the shoulder girdle remains in a good position.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.','https://www.youtube.com/embed/utpRpR6X2HA?rel=0','https://cdn.muscleandstrength.com/sites/default/files/dumbbell-high-low-carry.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (194,'Dumbbell Overhead Carry Video Exercise Guide','Forearms','Strength','Dumbbell','Compound','Isometric','Intermediate','Abs, Hamstrings, Lower Back, Quads, Shoulders, Traps, Upper Back','The dumbbell overhead carry is a variation of the farmers walk and an exercise used to strengthen the core and shoulders.
The dumbbell overhead carry provides a core stabilization challenge as you hold weight overhead and the core fights to stabilize the body as you walk for the predetermined number of steps.','Grasp a dumbbell in each hand using a neutral grip and stand up straight.
Either snatch or clean and press the dumbbells overhead to get into position.
While maintaining an active shoulder position, hold the dumbbell overhead and walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
If you sit in a position of heavy scapular depression, you may find that a slight shrug of the shoulder is necessary to get adequate upward rotation of the scapula and ensure the shoulder girdle remains in a good position.
If performing a unilateral carry variation, ensure that you’re not leaning to one side as you complete the movement.
Shrug the shoulder just slightly. Not enough so that it takes above a position of neutral but just enough to offset the weight pulling your shoulders down.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.','https://www.youtube.com/embed/Trkpt1jqQBA?rel=0','https://cdn.muscleandstrength.com/sites/default/files/dumbbell-overhead-carry.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (195,'Dumbbell Suitcase Carry Video Exercise Guide','Forearms','Strength','Dumbbell','Compound','Isometric','Beginner','Abs, Hamstrings, Quads, Shoulders, Traps, Upper Back','The dumbbell suitcase carry is a variation of the farmers walk and an exercise used to strengthen the core and forearms.
The unilateral loading seen in the dumbbell suitcase carry forces your core to fight to stabilize the spine.
The dumbbell suitcase carry gets its name because the way one holds the dumbbell while performing the exercise is reminiscent of the way one carries a suitcase.','Grasp a dumbbell in one hand using a neutral grip and stand up straight.
While maintaining an active shoulder position, hold the dumbbell by your side and walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
If performing a unilateral carry variation, ensure that you’re not leaning to one side as you complete the movement.
Shrug the shoulder just slightly. Not enough so that it takes above a position of neutral but just enough to offset the weight pulling your shoulders down.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.','https://www.youtube.com/embed/2BKmOGjE-d0?rel=0','https://cdn.muscleandstrength.com/sites/default/files/dumbbell-suitcase-carry.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (196,'Fat Gripz Dumbbell Farmers Carry Video Exercise Guide','Forearms','Strength','Dumbbell','Compound','Isometric','Beginner','Abs, Hamstrings, Quads, Shoulders, Traps, Upper Back','The Fat Gripz dumbbell farmers carry is a variation of the farmers carry and an exercise used to build the muscles of the forearms. The Fat Gripz dumbbell farmers carry will also indirectly target the muscles of the core and traps.
The Fat Gripz used during Fat Gripz dumbbell farmers carry makes the grip on the dumbbell larger and more difficult to hold. This in turn provides a greater forearm stimulus to help you build bigger forearms.','Wrap a set of fat gripz around a pair of dumbbells and grasp them using a neutral grip.
While maintaining an active shoulder position, hold the dumbbells by your side and walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
If performing a unilateral carry variation, ensure that you’re not leaning to one side as you complete the movement.
Shrug the shoulders just slightly. Not enough so that it takes above a position of neutral but just enough to offset the weight pulling your shoulders down.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.','https://www.youtube.com/embed/l50N5J4fHwk?rel=0','https://cdn.muscleandstrength.com/sites/default/files/fat-gripz-dumbbell-farmers-carry.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (197,'Forearm Extensors Lacrosse Ball Video Exercise Guide','Forearms','SMR','Lacrosse Ball','Isolation','Compression','Intermediate','None','Using a lacrosse ball to perform smr on your forearm extensors is a great way to warm up and cool down for your workout, especially if you plan to perform upper body exercises that require the forearms to be more mobile.
When you perform smr on the forearm extensors, or any muscle group for that matter, you alleviate some of the tension that is built up during the day and your workouts.','In a half kneeling position, place the lacrosse ball directly underneath the inside portion of your forearm and apply your free hand to the forearm to regulate pressure.
Slowly roll up and down the length of the forearm for 20-30 seconds.
Repeat on the other side.','The most important thing you can remember with any soft tissue work: KEEP BREATHING. Don’t hold your breath, you want to release tension, not generate it.
Do not allow yourself to fall into overextension, keep tension through the abs.
If you find a tender spot, pause for 5-6 seconds and focus on slow, deep breaths and try to relax.
Performing SMR may be uncomfortable but that’s not an excuse to avoid it. It hurts because there may be physiological or neurological influences generating a pain response. The more you roll the better it’ll feel provided there’s no serious underlying mechanism.
If you notice any burning, numbness, or tingling, keep moving past that area. It’s likely a nerve and pausing on it for any length of time would not be a good idea.
If you find a sensitive spot, pause for a second and take the joint through flexion and extension. This a method of active release known as “tack and floss”.','https://www.youtube.com/embed/_YuFsm9Cces?rel=0','https://cdn.muscleandstrength.com/sites/default/files/forearm-extensors-lacrosse-balls.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (198,'Forearm Tiger Tail Video Exercise Guide','Forearms','SMR','Tiger Tail','Isolation','Compression','Beginner','None','The tiger tail is an implement used to perform a form of self myo-fascial release.
Using the tiger tail on the forearms is a great way to warm up and cool down for your workout, especially if you plan to perform upper body exercises that require the forearms to be more mobile.
When you perform SMR on your forearms, or any muscle group for that matter, you alleviate some of the tension that is built up during the day and your workouts.','While in a seated position, position one end of the tiger tail on a solid surface and hold the other end in one hand.
Adjust pressure into forearm by using your bodyweight to bear down on the roller.
Slowly roll up and down the length of the forearm for 20-30 seconds.
Repeat for both the inner and outer portion of the forearm on both sides.','Given the tricep has flexors and extensors (much akin to the bicep and tricep causing opposing joint actions at the elbow), it would be wise to ensure that you’re completing soft tissue work on both aspects of the forearm.
The most important thing you can remember with any soft tissue work: KEEP BREATHING. Don’t hold your breath, you want to release tension, not generate it.
If you find a tender spot, pause for 5-6 seconds and focus on slow, deep breaths and try to relax.
In addition to some deep breathing, pause for a second and take the joint through flexion and extension. This a method of active release known as “tack and floss”.
Foam/stick rolling may be uncomfortable but that’s not an excuse to avoid it. It hurts because there may be physiological or neurological influences generating a pain response. The more you roll the better it’ll feel provided there’s no serious underlying mechanism.
HOWEVER, if you notice any burning, numbness, or tingling, keep moving past that area. It’s likely a nerve and pausing on it for any length of time would not be a good idea.','https://www.youtube.com/embed/Lf-w3hoqg4k?rel=0','https://cdn.muscleandstrength.com/sites/default/files/forearm-tiger-tail.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (199,'Kettlebell Single Arm Racked Carry Video Exercise Guide','Forearms','Strength','Kettle Bells','Compound','Isometric','Beginner','Abs, Hamstrings, Lower Back, Quads, Shoulders, Traps, Upper Back','The kettlebell single arm racked carry is a variation of the farmers walk and a total body exercise used to primarily target the muscles of the core, forearms, and traps.
The kettlebell single arm racked carry loads the weight unilaterally to force your core to stabilize your spine during the carry.
The kettlebell single arm racked carry is part of the loaded carry exercise family tree, which are important foundational exercises you should try to incorporate into your workout programs.','Grasp a kettlebell in one hand using a neutral grip and stand up straight.
Clean the kettlebell to get into position.
While maintaining an active shoulder position, hold the kettlebell in the front rack position and walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
When performing a unilateral carry variation, ensure that you’re not leaning to one side as you complete the movement.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.','https://www.youtube.com/embed/IxACM1FTPhc?rel=0','https://cdn.muscleandstrength.com/sites/default/files/kettlebell-single-arm-racked-carry.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (200,'Overhead Barbell Carry Video Exercise Guide','Forearms','Strength','Barbell','Compound','Isometric','Intermediate','Abs, Hamstrings, Lower Back, Quads, Shoulders, Traps, Upper Back','The overhead barbell carry is a variation of the farmers walk and a total body exercise used to strengthen the muscles of the core, forearms, and traps.
The overhead barbell carry stems from the loaded carry exercise family tree, which are all foundational exercises and one’s you should try to incorporate regularly in your own workout routines.','Set a bar at roughly chest height.
Set up facing away from the rack and unrack the bar at shoulder height in a overhead press position.
Press the bar to lockout and maintain a stable overhead position..
Walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
Shrug the shoulders just slightly. Not enough so that it takes above a position of neutral but just enough to offset the weight pulling your shoulders down.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.
With any barbell or trap bar variation, be very aware of your surroundings given this variation will require more room and is a bit more dangerous to those around you.','https://www.youtube.com/embed/_dMT8ROF6DE?rel=0','https://cdn.muscleandstrength.com/sites/default/files/overhead-barbell-carry.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (201,'Trap Bar Farmers Carry Video Exercise Guide','Forearms','Strength','Trap Bar','Compound','Isometric','Beginner','Abs, Hamstrings, Lower Back, Quads, Shoulders, Traps, Upper Back','The trap bar farmers carry is a variation of the farmers carry and is a full body exercise. In particular, the trap bar farmers carry can be used to strengthen and build the muscles of the core, forearms, and traps.
The trap bar farmers carry stems from the loaded carry exercise family tree, which are foundational movement patterns that should be included in your workout programs in one form or another.','Set up inside a trap bar with your feet hip width apart and your arms by your side.
Hinge forward and grasp the handles using a neutral grip.
Stand tall and extend the hips and knees to get into position.
While maintaining an active shoulder position, hold the trap bar and walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
Shrug the shoulders just slightly. Not enough so that it takes above a position of neutral but just enough to offset the weight pulling your shoulders down.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.
With any barbell or trap bar variation, be very aware of your surroundings given this variation will require more room and is a bit more dangerous to those around you.','https://www.youtube.com/embed/KjfjsmICipg?rel=0','https://cdn.muscleandstrength.com/sites/default/files/trap-bar-farmers-carry.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (202,'Trap Bar Overhead Carry Video Exercise Guide','Forearms','Strength','Trap Bar','Compound','Isometric','Intermediate','Abs, Hamstrings, Lower Back, Quads, Shoulders, Traps, Upper Back','The trap bar overhead carry is a variation of the farmers carry and is a full body exercise. In particular, the trap bar overhead carry can be used to strengthen and build the muscles of the core, forearms, and traps.
The trap bar overhead carry stems from the loaded carry exercise family tree, which are foundational movement patterns that should be included in your workout programs in one form or another.','Set up inside a trap bar that is positioned in a rack at just below shoulder height.
Unrack the weight while facing away from the rack and take 2 steps forward.
Press the weight overhead into position.
While maintaining an active shoulder position, keep the trap bar stabilized overhead and walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
Shrug the shoulders just slightly. Not enough so that it takes above a position of neutral but just enough to offset the weight pulling your shoulders down.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.
With any barbell or trap bar variation, be very aware of your surroundings given this variation will require more room and is a bit more dangerous to those around you.','https://www.youtube.com/embed/ya2Aq9MW40g?rel=0','https://cdn.muscleandstrength.com/sites/default/files/trap-bar-overhead-carry.jpg');
INSERT INTO exercise(id,name,target_muscle_group,exercise_type,equipment_required,mechanics,forcetype,experience_level,secondary_muscles,overview,instructions,tips,video,image) VALUES (203,'Zercher Carry Video Exercise Guide','Forearms','Strength','Barbell','Compound','Isometric','Intermediate','Abs, Hamstrings, Lower Back, Quads, Shoulders, Traps, Upper Back','The Zercher carry is a variation of the farmers carry and is a full body exercise. In particular, the Zercher carry can be used to strengthen and build the muscles of the core, forearms, and traps.
The Zercher carry stems from the loaded carry exercise family tree, which are foundational movement patterns that should be included in your workout programs in one form or another.','Set a bar at navel height or slightly below.
Set up facing away from the rack with the bar resting in the notch of your elbow just below the insertion of bicep.
Stand up tall and unrack the bar.
While maintaining an active shoulder position, keep the bar stabilized and walk for a designated distance or amount of time.','When setting up for the lift, ensure you take a good deep breath to set your shoulder position. The weight will drive your shoulders into scapular depression so you want to ensure that your shoulders are set in a good position prior to lifting the weight.
Shrug the shoulders just slightly. Not enough so that it takes above a position of neutral but just enough to offset the weight pulling your shoulders down.
Walk slowly and ensure a heel-toe pattern.
Stabilize the weight and don’t allow it to drive you into overextension.
Continue to breath throughout the exercise and don’t rely upon respiration for spinal stabilization.
With any barbell or trap bar variation, be very aware of your surroundings given this variation will require more room and is a bit more dangerous to those around you.','https://www.youtube.com/embed/pBfmjO-H9z0?rel=0','https://cdn.muscleandstrength.com/sites/default/files/zercher-carry.jpg');
