INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (1,'uhorka šalátová',14,0,0.82,2,1,0.18,0.07,0,0.01,0.09,0,0.93,0,97,18,41);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (2,'paradajky (rajčiny) cherry',21,0,0.9,4,3,0.2,0.03,0,0,0,0,1,0,0,0,45);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (3,'slepačie vajce',151,0,12,0.94,0.34,11,3,0,4,2,431,0,0,0,54,619);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (4,'káva espresso',4,0,0.2,0,0,0.4,0,0,0,0,0,0,0,0,2,10);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (5,'káva s mliekom bez cukru',12,'Káva obsahuje alkaloid kofeín, ktorý stimuluje centrálnu nervovú sústavu a srdcovú činnosť. Ide pravdepodobne o najrozšírenejšiu drogu na svete.
Káva odvodňuje organizmus, preto sa podáva s pohárom čistej vody.
Pokiaľ chcete z kávy vyťažiť maximálny pôžitok, zomeľte ju až tesne pred konzumáciou. Mletá káva si nedokáže dlhšie udržať svoju arómu.',0.5,1,1,0.7,0,0,0,0,0,0,0,0,0,25);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (6,'voda z vodovodu',0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (7,'šunka bravčová dusená najvyššej akosti',118,0,19,0.5,0,4,0,0,0,0,0,0,1,0,0,950);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (8,'banány',94,0,1,22,19,0.2,0.1,0,0.02,0.1,0,2,0,74,12,60);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (9,'zemiaky varené bez šupky',85,0,2,19,0,0.1,0.04,0,0,0,0,1,0.07,0,27,66);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (10,'voda pitná',0,'Čistá voda by mala byť číra, bez chuti a bez zápachu.
Voda je nevyhnutná pre všetky funkcie organizmu. Nedostatok tekutín sa prejavuje najčastejšie bolesťami hlavy alebo zmenou nálady.
V horúčavách smäd najlepšie zaženie čistá voda, nemala by byť však ľadová.',0,0,0,0,0,0,0,0,0,0,0,100,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (11,'mandarínky',43,0,0.72,12,9,0.3,0,0,0,0,0,2,0,0,0,36);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (12,'rožok biely',287,'Tukové rožky sa vyrábajú z pšeničnej múky, vody, tuku (olej / margarín), droždia, soli a často aj z množstva prídavných látok (zlepšujúce prípravky, emulgátory, protihrudkujúce látky ai.).
Tukový rožok dodá telu iba prázdne kalórie. Je vyrobený z vymletej múky, ktorá je zbavená väčšiny vitamínov a minerálnych látok a obsah vlákniny v nej je zanedbateľný.
V jedálničku uprednostňujeme pečivo z celozrnnej múky a to bez obsahu prídavných látok. Biele pečivo uprednostňujte u malých detí.',9,55,1,3,0.6,0,0,0,0,2,1,0,0,450);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (13,'rajčiny / paradajky',25,0,0.96,4,3,0.23,0.04,0,0.03,0.1,0,2,0,94,0,48);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (14,'mrkva',35,0,1,7,6,0.22,0.04,0,0,0.12,0,4,0,88,45,50);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (15,'paprika červená',35,0,1,6,4,0.3,0.06,0,0,0,0,2,0,0,0,50);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (16,'jablká',63,0,0.37,13,11,0.4,0.23,0,0.01,0.22,0,3,0,85,8,18);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (17,'Eidam syr 30% tuku, plátky',263,0,30,1,0.1,15,10,0,0,0,0,0,2,0,690,1515);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (18,'čaj ovocný bez cukru',3,0,0.5,0.7,0,0.5,0,0,0,0,0,0,0,0,0,25);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (19,'paradajky (rajčiny) cherry',21,0,0.9,4,3,0.2,0.03,0,0,0,0,1,0,0,0,45);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (20,'chlieb konzumný rascový krájaný',244,0,8,45,0,1,0,0,0,0,60,4,0,0,0,400);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (21,'káva turecká',6,0,0.1,1,0,0.04,0,0,0,0,0,0,0.01,0,0,5);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (22,'olej olivový extra panenský',819,0,0,0,0,91,12,6,65,9,0,0,0,0,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (23,'kapia sladká paprika',27,'Pozitívny vplyv na zdravie',0.9,5,2,0.2,0.1,0,0,0.1,0,2,0,0,0.01,45);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (24,'ovsené vločky',400,0,13,68,2,7,1,0,3,3,0,7,0,10,57,657);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (25,'káva rozpustná, bez cukru, nápoj',2,0,0.1,0.4,0,0,0,0,0,0,0,0,0,99,0,5);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (26,'chlieb ražný',241,0,8,48,2,1,0.1,0,0,0,0,6,2,0,0,375);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (27,'kuracie prsia restované',184,0,29,0.6,0,7,2,0,3,2,89,0,0,0,15,1050);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (28,'med včelí',333,0,0.27,82,80,0.04,0.01,0,0.02,0.01,0,0,0,18,5,13);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (29,'bylinkový čaj',0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (30,'praženica (vajcia miešané)',166,0,12,2,0,12,4,0,5,2,383,0,0,73,66,622);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (31,'tvaroh odtučnený Pilos',69,0,12,4,4,0.3,0.2,0,0,0,0,0,0.1,0,90,590);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (32,'reďkovka',24,0,1,4,2,0.14,0.03,0,0.02,0.06,0,2,0,94,40,54);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (33,'Chia semienka',495,0,21,20,4,31,3,0,2,20,0,41,0.01,6,545,1060);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (34,'rozpustná káva s mliekom',15,0,0.95,2,1,0.4,0.18,0,0,0,0,0,0,0,0,30);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (35,'cibuľa',43,0,1,9,6,0.25,0.09,0,0,0.11,0,3,0,88,37,71);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (36,'High Protein Pudding Chocolate Milbona',77,0,10,5,4,2,1,0,0,0,0,0,0.12,0,0,500);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (37,'mlieko plnotučné 3,5%',64,0,3,5,5,4,2,0,0.97,0.12,0,0,0,88,118,161);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (38,'jazmínová ryža varená',113,0,3,25,0,0.2,0,0,0,0,0,0.5,0,0,0,135);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (39,'čaj zelený bez cukru',0.4,'Zelený čaj sa vyrába z povädnutých zvinutých čajových lístkov, ktoré sa nechajú vysušiť. Obsahuje vitamíny B a C; triesloviny, vďaka ktorým má trpkú chuť. Je to výborný zdroj antioxidantov, katechínov, polyfenolov a LTheanínu.
Podľa niektorých zdrojov pravidelné popíjanie kvalitného zeleného čaju napomáha pri redukcii hmotnosti tým, že zvyšuje energetický výdaj organizmu. Konzumácia zeleného čaju je podľa japonskej vedeckej štúdie z roku 2006 spojená so znížením úmrtnosti zapríčinených rakovinou.
Pre prípravu naozaj kvalitného zeleného čaju uprednostnite sypané čaje pred vrecúškovými. Poobzerajte sa v špecializovaných predajniach, čajovniach, kde nájdete bohatú ponuku i vyškolený personál, ktorý vám poradí a pomôže pri výbere. Pre "začiatočníkov" sú vhodnou voľbou menej výrazné druhy čajov, na rozdiel od zákazníkov, ktorí už majú s chuťou zeleného čaju mnoho skúseností.',0,0.1,0,0,0,0,0,0,0,0,0,100,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (40,'voda s citrónom',2,'Pozitívny vplyv na zdravie',0,0.4,0,0,0,0,0,0,0,0.1,0,100,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (41,'Madeta juhočeské maslo',731,0,0.8,0.8,0.8,82,54,0,0,0,274,0,0.02,0,0,40);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (42,'rožok biely',287,'Tukové rožky sa vyrábajú z pšeničnej múky, vody, tuku (olej / margarín), droždia, soli a často aj z množstva prídavných látok (zlepšujúce prípravky, emulgátory, protihrudkujúce látky ai.).
Tukový rožok dodá telu iba prázdne kalórie. Je vyrobený z vymletej múky, ktorá je zbavená väčšiny vitamínov a minerálnych látok a obsah vlákniny v nej je zanedbateľný.
V jedálničku uprednostňujeme pečivo z celozrnnej múky a to bez obsahu prídavných látok. Biele pečivo uprednostňujte u malých detí.',9,55,1,3,0.6,0,0,0,0,2,1,0,0,450);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (43,'chlieb pšenično ražný',217,0,8,42,3,1,0.2,0,0,0,0,5,1,0,23,400);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (44,'kaiserka cereálna',262,0,10,43,2,5,1,0,0,0,0,3,1,0,0,500);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (45,'kaša zemiaková',115,0,3,19,4,3,2,0,0.76,0.19,0,1,0.98,76,0.06,135);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (46,'cestoviny varené',133,0,4,24,0.2,3,0.31,0,0.84,1,0,1,0.41,69,11,177);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (47,'tvaroh odtučnený Pilos',69,0,12,4,4,0.3,0.2,0,0,0,0,0,0.1,0,90,590);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (48,'avokádo čerstvé',171,0,2,9,0.4,13,3,0,7,2,0,5,0,68,12,95);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (49,'Hollandia jogurt gazdovský biely 3,5 % tuku',67,0,4,4,3,4,3,0,0,0,0,0,0.12,0,125,185);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (50,'Slatinský chlieb celozrnný 100% Slatinské pekárne',195,0,11,33,0.8,0.5,0.1,0,0,0,0,9,2,0,4,550);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (51,'orechy vlašské',718,0,16,18,4,63,7,0,12,45,0,6,0,4,96,788);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (52,'zelenina čerstvá rajčiny, uhorky, ľadový šalát',21,'Pozitívny vplyv na zdravie',0.8,3,0.2,0,0,0,0,0,0,3,0,0,22,40);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (53,'čaj',0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (54,'čučoriedky',44,0,1,8,8,0.6,0,0,0,0,0,3,0,86,18,55);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (55,'kuracie stehno pečené',145,0,25,0,0,5,2,0,0,0,0,0,0,0,0.03,1250);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (56,'čaj černý bez cukru',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (57,'Fit den Večerní chlebík Penam',263,0,28,2,0.9,14,2,0,0,0,0,11,1,0,0,1400);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (58,'tvaroh polotučný Pilos',91,'Negatívny vplyv na zdravie',10,4,4,4,2,0,0,0,0,0,0.1,0,100,500);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (59,'kaleráb biely',28,0,2,4,3,0.14,0.03,0,0.01,0.07,0,3,0.1,92,24,60);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (60,'knedľa žemľová',212,0,7,42,2,2,0.7,0,0.5,0.39,12,1,1,47,57,345);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (61,'paprika žltá',30,0,1,5,4,0.39,0,0,0,0,0,2,0,0,0,50);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (62,'Klasik jogurt biely 2,7% Olma',60,0,5,4,4,3,2,0,0,0,0,0,0.13,0,125,245);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (63,'paradajky cherry kríčkové balené',24,0,1,4,2,0.2,0,0,0,0,0,1,0,0,0,50);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (64,'Tortilla Wraps celozrnná Lidl',295,0,10,45,3,7,2,0,0,0,0,6,1,0,0,475);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (65,'víno biele suché',63,0,0.1,0.4,0.4,0,0,0,0,0,0,0,0,0,0,5);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (66,'žemľa obyčajná',288,0,8,60,0,1,0,0,0,0,0,3,1,0,0,420);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (67,'100% Whey protein Nutrend',378,0,76,7,5,4,3,0,0,0,0,1,2,0,0,3780);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (68,'Gervais FitProtein',144,'Gervais FitProtein se skládá z tvarohu, pitné vody, jedlé soli a zahušťovadla (pektiny, karubin). Obsahuje také laktózu, kyselinu mléčnou (regulátor kyselosti) a karagenan (stabilizátor).
Mléčné výrobky jsou zdrojem vápníku, který je důležitým minerálním prvkem pro náš organismus, protože se podílí na pevnosti kostí a zubů, i podporuje funkci nervů, svalů a srdce. Jsou také bohaté na bílkoviny, které podporují růst a vývoj svalové hmoty.
Gervais FitProtein je určen především k namazání pečiva. V obchodě si vybírejte si kvalitní celozrnné výrobky nebo 100% žitný chléb. Pokud vás baví trávit čas v kuchyni, tak si můžete zkusit upéct třeba vlastní celozrnné housky. Další využití žervé může být do pomazánek, dresinků nebo dipů.',8,2,2,12,8,0,0,0,0,0,0.75,0,0,375);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (69,'orechy kešu natural',583,0,17,26,5,46,10,0,26,7,0,2,0,4,32,872);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (70,'kečup jemný Hellmann´s',109,0,1,24,21,0.5,0.1,0,0,0,0,0,2,0,0,60);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (71,'tvarůžky Harzbube Handkäse',126,0,30,0.1,0.1,0.5,0.2,0,0,0,0,0,3,0,0,1500);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (72,'cukor biely',401,0,0,100,100,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (73,'Chlieb toastový tmavý viaczrnný Penam',278,0,10,49,2,4,0.5,0,0,0,0,4,1,0,0,475);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (74,'hroznové víno bílé bezsemenné',76,0,0.6,17,16,0.4,0.1,0,0,0.1,0,0.9,0,0,14,30);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (75,'Jogurt gréckeho typu biely 0.3% tuku',58,'Pozitívny vplyv na zdravie',10,4,4,0.3,0.2,0,0,0,0,0,0.1,0,125,500);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (76,'Wholegrain toast (toastový pšeničný celozrnný chlieb) Tastino',267,0,9,42,4,6,0.5,0,0,0,0,6,1,0,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (77,'čučoriedky kanadské',57,0,0.74,12,10,0.33,0.03,0,0.05,0.15,0,2,0,84,6,37);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (78,'kuracia prsná šunka 92% Pikok pure',92,0,19,0.5,0.4,1,0.4,0,0,0,75,0,2,0,14,965);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (79,'vločky oat flakes fine Crownfield',354,0,12,61,1,5,0.8,0,0,0,0,9,0.01,0,0,600);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (80,'zelenina priemer',27,0,1,4,2,0.34,0.03,0,0,0,0,2,0,0,22,50);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (81,'zemiaková kaša s mliekom a maslom',114,0,2,17,2,4,2,0,0,0,0,1,0.75,0,6,94);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (82,'morčacia šunka 92% mäsa pure Pikok',85,0,19,0.5,0.1,0.6,0.2,0,0,0,0,0,2,0,0,955);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (83,'paradajky (rajčiny) cherry oválne',21,0,0.9,3,2,0.2,0,0,0,0,0,2,0,0,0,45);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (84,'slnečnicový olej',897,0,0.1,0.1,0,100,12,0,30,59,0,0,0,0.3,0,5);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (85,'CocaCola Zero',0.21,'Negatívny vplyv na zdravie',0,0,0,0,0,0,0,0,0,0,0.02,0,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (86,'kurací rezeň vyprážaný',310,0,22,15,0.98,18,8,0,8,2,99,1,2,26,51,1096);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (87,'káva s cukrom a mliekom',42,0,1,6,5,2,1,0,0,0,0,0,0,0,0,55);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (88,'jogurt biely krémový 3,7% Pilos',66,0,4,4,4,4,3,0,0,0,0,0,0.1,0,125,195);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (89,'ryža Basmati',359,0,7,80,0,0.4,0,0,0,0,0,4,0,0,0,335);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (90,'Žitný kváskový chléb Breadway',195,0,7,34,2,2,0.2,0,0,0,0,4,2,0,0,330);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (91,'jogurt biely krémový 3,7% Pilos',66,0,4,4,4,4,3,0,0,0,0,0,0.1,0,125,195);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (92,'cesnak',130,0,6,25,3,0.27,0.06,0,0.01,0.16,0,2,0,61,35,310);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (93,'toustový chlieb svetlý',264,0,10,51,1,2,0.56,0,0,0,0,2,0,0,0,485);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (94,'Jihočeský cottage natur Madeta',119,0,11,3,3,7,5,0,0,0,0,0,0.7,0,80,550);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (95,'hranolky',275,0,4,35,0.6,12,2,0,0,0,0.2,3,0.57,0,10,195);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (96,'jablko Gala',54,0,0.2,11,8,0.4,0,0,0,0,0,2,0,0,7,10);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (97,'Lučina čerstvá ako prechádzka rannou rosou',270,0,7,2,2,26,15,0,0,0,0,0,0.55,0,150,365);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (98,'Protein Tvarohová tyčinka v kakaové polevě Pilos',309,0,22,16,7,19,14,0,0,0,0,0,0.1,0,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (99,'chlieb domáci kváskový, pšenično ražný',176,0,6,35,0.4,0.8,0.2,0,0,0,0,2,0.01,0,6,300);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (100,'pomazánkové maslo choceňské',310,'Choceňská nátierkové maslo je vyrobené z kyslej smotany, sušeného mlieka, sušenej srvátky, zemiakového škrobu a soli.
Pri umiernené spotrebe nemôže nátierkové maslo určite uškodiť nášmu zdraviu. Možno ho využiť aj pri rôznych typoch diét (redukčná diéta, diabetická diéta, šetriace diéta a i.).
Neochutené nátierkového maslo môžete ozvláštniť pridaním ďalších ingrediencií. Výborne sa hodí napríklad čerstvé bylinky, cesnak, chren, vňaťová cibuľka alebo napríklad kúsky kvalitnej šunky, údený losos, strúhaný syr ai. Okrem toho, že je taká nátierka zakaždým originálne, vyhnete sa konzumácii nežiaducich látok, ktoré by ste prijali v podobnom, komerčne vyrábanom produktu.',3,6,3,31,21,0,0,0,0,0,0.6,0,0,165);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (101,'Magnesia minerálna voda jemne perlivá',0,0,0,0,0,0,0,0,0,0,0,0,0.04,100,4,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (102,'Gervais original',186,0,6,3,3,17,12,0,0,0,0,0,0.73,0,0,300);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (103,'špagety varené',142,0,5,28,0.56,0.67,0.18,0,0,0,0,2,0,0,7,238);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (104,'eidamska tehla 30%',254,0,27,0.5,0.5,16,10,0,0,0,0,0,2,0,740,1350);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (105,'kuracie mäso pečené',146,0,20,0,0,7,2,0,3,2,90,0,0,64,0.02,1000);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (106,'pivo Pilsner Urquell',43,0,0.5,5,0.5,0,0,0,0,0,0,0.25,0,0,0,0.04);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (107,'hovädzí vývar s mäsom a rezancami',56,'Pozitívny vplyv na zdravie',4,7,0,1,0,0,0,0,0,1,1,0,0,195);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (108,'škorica mletá',234,0,4,28,0,2,0,0,0,0.8,0,53,0.06,9,1437,196);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (109,'čaj čierny s citrónom',0.4,0,0,0.1,0.1,0,0,0,0,0,0,0,0,100,0.1,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (110,'ovsené vločky jemné s vlákninou Emco',346,0,15,52,2,5,0.9,0,1,2,0,16,0,0,0,750);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (111,'Skyr Natur Pilos 0.1',62,0,12,3,3,0.1,0.1,0,0,0,0,0,0.1,0,0,600);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (112,'cappuccino',33,'Pozitívny vplyv na zdravie',2,3,3,1,1,0,0,0,0,0,0,0,0,425);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (113,'rožky celozrnné',299,0,9,55,0,3,0.88,0,0.91,0.82,0,10,0,31,55,450);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (114,'tuniak vo vlastnej šťave',101,0,23,0.1,0,1,0.9,0,0,0,30,0,1,74,8,1150);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (115,'voda so šťavou',9,'Sirup je zdrojom množstva jednoduchých sacharidov vo forme cukru, glukózovofruktózového sirupu alebo umelých sladidiel (niekedy v kombinácii). Väčšinou sa pridávajú aj ďalšie nežiadúce látky, ako sú rôzne farbivá, arómy alebo konzervačné látky.
V sirupoch sa zvyčajne nenachádza nič, čo by mohlo pozitívne ovplyvniť naše zdravie. Pravidelná konzumácia väčšieho množstva sladenej vody alebo vody s umelými sladidlami je nevhodná a zaťažuje naše telo. Častá konzumácia veľkého množstva sirupu s cukrom prispieva aj k obezite (týka sa to najmä detí s genetickou predispozíciou, ktoré konzumujú aj mnoho ďalších nevhodných jedál a nápojov a nemajú dostatok pohybu) a k vzniku ďalších pridružených chorôb.
Vodu so sirupom skúste nahradiť vodou s pridanou čerstvou pomarančovou alebo inou ovocnou šťavou, alebo skúste vodu, v ktorej ste vylúhovali pokrájané kúsky ovocia (môžete použiť aj zeleninu, napr. šalátovú uhorku), pite bylinné alebo ovocné čaje, alebo len čistú vodu. Takéto nápoje môžu byť prínosom pre váš organizmus, pretože obsahujú cenné látky.',0,2,2,0,0,0,0,0,0,0,0,100,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (116,'horčica plnotučná',102,'Negatívny vplyv na zdravie',6,7,5,5,0,0,0,0,0,1,2,0,0,280);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (117,'morčacie prsia restované',107,0,20,0.1,0,3,0,0,0,0,0,0,0,0,0,1000);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (118,'High Protein Pudding Vanilla Milbona',75,0,10,5,4,2,1,0,0,0,0,0,0.12,0,0,500);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (119,'mozzarella light Galbani',165,0,19,2,1,9,6,0,0,0,0,0,0.7,0,1,950);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (120,'mozzarella Galbani',236,0,17,2,1,18,13,0,0,0,0,0,0.7,0,0,850);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (121,'mango',75,0,0.6,16,12,0.45,0.1,0,0.18,0.08,0,2,0,82,0.01,30);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (122,'Latte Macchiato nesladené',34,0,2,3,3,2,1,0,0,0,0,0.1,0,0,0,90);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (123,'pečené bravčové mäso chudé',174,0,30,0,0,6,2,0,0,0,0,0,2,0,0,1500);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (124,'zeleninový šalát bez zálievky priemer',49,'Zelenina je pre človeka dôležitým zdrojom vitamínov, minerálov, vlákniny, vody a iných prospešných látok. Z hlavných živín sú najviac zastúpené sacharidy.
Vitamíny, minerály, vláknina a ďalšie látky obsiahnuté v zeleninovom šaláte sú výbornou ochranou pred infekciami, rakovinou, srdcovocievnymi ochoreniami ai. Nízka energetická hodnota na pomerne veľké množstvo a bohaté zastúpenie výživných látok robí zo zeleninového šalátu skvelý doplnok väčšiny hlavných jedál nielen pri racionálnej , ale aj pri redukčnej či diabetickej diéte. Vhodne doplnené zeleninové šaláty môžu poslúžiť aj ako hlavný chod.
Aby vaše telo mohlo využiť aj vitamíny rozpustné v tukoch, pokvapkajte zeleninový šalát kvalitným olejom (panenský olivový, avokádový, orechový ...) alebo pridajte ďalších zložiek, ktorá obsahuje tuk (syr, orechy, semienka, údená ryba a i.).',2,8,0,0.52,0,0,0,0,0,2,0,0,0,105);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (125,'repkový olej',898,0,0.1,0.1,0,100,7,0,62,29,0,0,0,0.2,0,5);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (126,'voda perlivá',0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (127,'žervé klasik Pilos',204,0,10,6,4,16,10,0,0,0,0,0,1,0,0,500);
INSERT INTO food(id,name,energy_value,details,protein,carbohydrates,sugars,fats,saturated_fatty_acids,trans_fatty_acids,monounsaturated,semi_saturated,cholesterol,fiber,salt,water,calcium,phe) VALUES (128,'Pražská šunka 92% mäsa najvyššia akosť LE & CO',109,0,19,0.8,0.1,3,0.8,0,0,0,0,0,2,0,0,945);
